language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

sudo: false

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  - composer --verbose update
  - cd $TRAVIS_BUILD_DIR/app
  - ./../vendor/bin/drush site-install --verbose --yes --root=app/core --uri=127.0.0.1:8080 --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush runserver --root=app/core --uri=127.0.0.1:8080 http://127.0.0.1:8080 &
  - sleep 3
  - ./../vendor/bin/drush core-status --root=app/core --uri=127.0.0.1:8080
