---

stack:
    php:
        launch: false
        proto: http
        host: 127.0.0.1
        port: 8080
    sql:
        type: mysql
        prefix:
    mysql:
        host: 127.0.0.1
        port: 3306
        suname: root
        supass: test
        username: drupal
        password: test
        database: drupal_local

application:
    basic:
        uri: example.local
