---

stack:
    php:
        launch: false
        proto: http
        host: staging.example.com
        port: 80
    sql:
        type: mysql
        prefix:
    mysql:
        host: mysql.example.com
        port: 3306
        suname: root
        supass: test
        username: drupal
        password: test
        database: drupal_staging

application:
    basic:
        uri: staging.example.com
